[package]
name = "portablegit-rs"
version = "50.1.0+2.44.0.windows.1"
edition = "2021"

[dependencies]
self-replace = "1.3.7"
xdg = "2.5.2"
xshell = "0.2.6"

[build-dependencies]
xdg = "2.5.2"
xshell = "0.2.6"
